kind: pipeline
type: docker
name: rce

steps:
- name: build-rce
  image: docker
  commands:
  - docker --version
  - docker build --no-cache -t rce-${DRONE_COMMIT} .
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock

- name: test-rce
  image: rce-${DRONE_COMMIT}
  pull: if-not-exists
  commands:
    - npm run test

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
